# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 1.0
default_acceleration_scaling_factor: 1.0

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  left_base_pitch_joint:
    has_velocity_limits: true
    max_velocity: 50.0
    has_acceleration_limits: true
    max_acceleration: 1.0
  left_elbow_pitch_joint:
    has_velocity_limits: true
    max_velocity: 50.0
    has_acceleration_limits: true
    max_acceleration: 1.0
  left_gripper1_joint:
    has_velocity_limits: true
    max_velocity: 50.0
    has_acceleration_limits: true
    max_acceleration: 1.0
  left_gripper2_joiint:
    has_velocity_limits: true
    max_velocity: 50.0
    has_acceleration_limits: true
    max_acceleration: 1.0
  left_shoulder_roll_joint:
    has_velocity_limits: true
    max_velocity: 50.0
    has_acceleration_limits: true
    max_acceleration: 1.0
  left_shoulder_yaw_joint:
    has_velocity_limits: true
    max_velocity: 50.0
    has_acceleration_limits: true
    max_acceleration: 1.0
  left_wrist_pitch_joint:
    has_velocity_limits: true
    max_velocity: 50.0
    has_acceleration_limits: true
    max_acceleration: 1.0
  left_wrist_yaw_joint:
    has_velocity_limits: true
    max_velocity: 50.0
    has_acceleration_limits: true
    max_acceleration: 1.0
  neck_pitch_joint:
    has_velocity_limits: true
    max_velocity: 50.0
    has_acceleration_limits: true
    max_acceleration: 1.0
  neck_yaw_joint:
    has_velocity_limits: true
    max_velocity: 50.0
    has_acceleration_limits: true
    max_acceleration: 1.0
  right_base_pitch_joint:
    has_velocity_limits: true
    max_velocity: 50.0
    has_acceleration_limits: true
    max_acceleration: 1.0
  right_elbow_pitch_joint:
    has_velocity_limits: true
    max_velocity: 50.0
    has_acceleration_limits: true
    max_acceleration: 1.0
  right_gripper1_joint:
    has_velocity_limits: true
    max_velocity: 50.0
    has_acceleration_limits: true
    max_acceleration: 1.0
  right_gripper2_joint:
    has_velocity_limits: true
    max_velocity: 50.0
    has_acceleration_limits: true
    max_acceleration: 1.0
  right_shoulder_roll_joint:
    has_velocity_limits: true
    max_velocity: 50.0
    has_acceleration_limits: true
    max_acceleration: 1.0
  right_shoulder_yaw_joint:
    has_velocity_limits: true
    max_velocity: 50.0
    has_acceleration_limits: true
    max_acceleration: 1.0
  right_wrist_pitch_joint:
    has_velocity_limits: true
    max_velocity: 50.0
    has_acceleration_limits: true
    max_acceleration: 1.0
  right_wrist_yaw_joint:
    has_velocity_limits: true
    max_velocity: 50.0
    has_acceleration_limits: true
    max_acceleration: 1.0