# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - right_arm_controller
    - left_arm_controller
    - left_gripper_controller
    - right_gripper_controller
    - neck_controller

  right_arm_controller:
    type: FollowJointTrajectory
    joints:
      - right_base_pitch_joint
      - right_shoulder_roll_joint
      - right_shoulder_yaw_joint
      - right_elbow_pitch_joint
      - right_wrist_pitch_joint
      - right_wrist_yaw_joint
    action_ns: follow_joint_trajectory
    default: true

  left_arm_controller:
    type: FollowJointTrajectory
    joints:
      - left_base_pitch_joint
      - left_shoulder_roll_joint
      - left_shoulder_yaw_joint
      - left_elbow_pitch_joint
      - left_wrist_pitch_joint
      - left_wrist_yaw_joint
    action_ns: follow_joint_trajectory
    default: true

  left_gripper_controller:
    type: FollowJointTrajectory
    joints:
      - left_gripper1_joint
    action_ns: follow_joint_trajectory
    default: true

  right_gripper_controller:
    type: FollowJointTrajectory
    joints:
      - right_gripper1_joint
    action_ns: follow_joint_trajectory
    default: true

  neck_controller:
    type: FollowJointTrajectory
    joints:
      - neck_pitch_joint
      - neck_yaw_joint
    action_ns: follow_joint_trajectory
    default: true