# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    right_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    left_gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    right_gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    neck_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

right_arm_controller:
  ros__parameters:
    joints:
      - right_base_pitch_joint
      - right_shoulder_roll_joint
      - right_shoulder_yaw_joint
      - right_elbow_pitch_joint
      - right_wrist_pitch_joint
      - right_wrist_yaw_joint
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
left_arm_controller:
  ros__parameters:
    joints:
      - left_base_pitch_joint
      - left_shoulder_roll_joint
      - left_shoulder_yaw_joint
      - left_elbow_pitch_joint
      - left_wrist_pitch_joint
      - left_wrist_yaw_joint
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
left_gripper_controller:
  ros__parameters:
    joints:
      - left_gripper1_joint
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
right_gripper_controller:
  ros__parameters:
    joints:
      - right_gripper1_joint
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
neck_controller:
  ros__parameters:
    joints:
      - neck_pitch_joint
      - neck_yaw_joint
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity